# Generated by Django 4.1 on 2023-11-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название товара', max_length=255, verbose_name='Название')),
                ('description', models.TextField(help_text='Введите описание товара', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите стоимость товара в рублях', max_digits=8, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'item',
            },
        ),
    ]
