version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: web
    volumes:
      - .:/src
    restart: always
    depends_on:
      - database
    ports:
      - "8000:8000"
    env_file:
      - .env

  database:
    image: postgres
    container_name: database
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: